import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import NavBar from "../components/NavBar";

// Font files can be colocated inside of `app`

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "Mouhami",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin-ext"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <NavBar />
        <div className="text-black">{children}</div>
      </body>
    </html>
  );
}
