import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";

// Font files can be colocated inside of `app`

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "Survision App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className=" ">
      <body>
        <NavBar />
        <div className="">{children}</div>
      </body>
    </html>
  );
}
